apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
# Image automation - Flux will update the newTag automatically
images:
  - name: stefanprodan/podinfo
    newTag: stefanprodan/podinfo:6.9.1 # {"$imagepolicy": "flux-system:podinfo"}
